#!/bin/bash
sudo mkdir /opt/mine-fabric/ || exit 1
sudo chown -R $USER:$USER /opt/mine-fabric
cd /opt/mine-fabric/
initmine fabric
mv server.jar fabric-installer.jar
java -jar /opt/mine-fabric/fabric-installer.jar server
echo '#!/bin/sh
# This script is run by systemd so you can edit anything related to the server startup here without using root and messing up something with systemd
# makes the script runnable from anywhere on the system
BINDIR=$(dirname "$(readlink -fn "$0")")
cd "$BINDIR"
# INITIAL_MEM is how much memory you want java to start with. You can edit it with G (gigabytes) or m (megabytes)
INITIAL_MEM="1G"
# MAX_MEM is the same thing as above except it is the hard limit on how much memory java will run with. If INITIAL_MEM and MAX_MEM are the same it will help with garbage collecting.
MAX_MEM="1G"
# Put flags in between the quotes below
FLAGS=""
# nogui is at the end because without it will suck all your available ram. The -server flag is to tell java to conserve ram and cpu as much as possible
java -jar -server -Xms$INITIAL_MEM -Xmx$MAX_MEM $FLAGS fabric-server-launch.jar nogui' > start.sh
exit
